config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "diaries#index"
  resources :diaries do
    collection do
      get 'search'
    end
  end

  resources :users, only: :show do
    resources :calendars, only: [:index,:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
  with_options presence: true do
    validates :start_time
    validates :site
  end

  belongs_to :user
  has_one :calendar
  has_one_attached :image

  has_many :workouts, dependent: :destroy
  accepts_nested_attributes_for :workouts, allow_destroy: true

  def self.search(search)
    if search != ""
      Diary.where('site LIKE(?) OR menu LIKE(?) OR nickname LIKE(?)', "%#{search}%","%#{search}%","%#{search}%")
    else
      Diary.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :diaries
  has_many :calendars
  with_options presence: true do
    validates :nickname
    validates :first_name, format: { with: /\A[ぁ-んァ-ヶー-龥々ー]+\z/.freeze, message: 'は全角文字で入力してください' }
    validates :last_name, format: { with: /\A[ぁ-んァ-ヶー-龥々ー]+\z/.freeze, message: 'は全角文字で入力してください' }
    validates :first_name_kana,
              format: { with: /\A[ァ-ヶー－]+\z/.freeze, message: 'は全角文字のカタカナで入力してください' }
    validates :last_name_kana,
              format: { with: /\A[ァ-ヶー－]+\z/.freeze, message: 'は全角文字のカタカナで入力してください' }
    validates :birthday
  end

  validates :password,
            format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze, message: 'は半角英数字を混合して入力してください' }
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :diary

  validates :set, presence: true, numericality: { only_integer: true, message: 'は半角数字で入力してください' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:nickname, :first_name, :last_name, :first_name_kana, :last_name_kana,
                                             :birthday])
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = User.find(current_user.id)
    @diaries = @user.diaries
  end

  def show
    @user = User.find(params[:user_id])
    @diaries = @user.diaries
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :set_diary, only: [:show, :edit, :update, :destroy]

  def index
    @diaries = Diary.includes(:user).order('created_at DESC')
  end

  def new
    @diary = Diary.new
    @workout = @diary.workouts.build
  end

  def create
    @diary = Diary.new(diary_params)
    if @diary.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @workouts = Workout.where(diary_id: params[:id])
  end

  def edit
    redirect_to root_path unless @diary.user_id == current_user.id
  end

  def update
    if @diary.update(diary_params)
      redirect_to diary_path
    else
      render :edit
    end
  end

  def destroy
    if @diary.user_id == current_user.id && @diary.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def search
    @diaries = Diary.includes(:user,:workouts).references(:user,:workouts).search(params[:keyword]).order('diaries.created_at DESC')
  end

  private

  def diary_params
    params.require(:diary).permit(:start_time, :site, :image,
                                  workouts_attributes: [:id, :diary_id, :menu, :weight, :rep, :set, :_destroy]).merge(user_id: current_user.id)
  end

  def set_diary
    @diary = Diary.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
    @diaries = @user.diaries
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calendars/index.html.erb
<%= render 'shared/second-header'%>
<div class="text-center fs-2"><%= @user.nickname%>の頻度カレンダー
</div>
<%= month_calendar events: @diaries do |date,diaries|%>
  <%= date.day%>
  <% diaries.each do |diary|%>
    <div>
      <%= link_to "#{diary.site}", diary_path(diary), class: "link-dark text-decoration-none" %>
    </div>
  <%end%>
<% end %>

<%= render 'shared/second-footer' %>

app/views/calendars/show.html.erb
<%= render 'shared/second-header'%>
<div class="text-center fs-2 pt-3 mb-4"><%= @user.nickname%>の頻度カレンダー
</div>
  <%= month_calendar events: @diaries do |date,diaries|%>
    <%= date.day%>
    <% diaries.each do |diary|%>
      <div>
        <%= link_to "#{diary.site}", diary_path(diary), class: "link-dark text-decoration-none" %>
      </div>
    <%end%>
  <% end %>

<%= render 'shared/second-footer' %>

app/views/diaries/_diary.html.erb
<div class="container bg-screen">
  <div class= "p-4 p-md-5 pb-4 text-white">
    <div class="col-md-8 px-0">
      <p class="display-4 fst-italic fs-2">Fitness is not about being better than someone else. It’s about being better than you used to be.</p>
      <p class="fs-4">ー フィットネスは、他人より優れることが重要ではない。かつての自分を超越するものだ。</p>
    </div>
  </div>
</div>
<div class="bg-light">
  <div class="fs-2 text-center pt-4">ワークアウト記録一覧
  </div>
  <div class="container">
    <div class="row row-cols-1 row-cols-md-2">
      <% @diaries.each do |diary|%>
        <div class="col">
          <%= link_to diary_path(diary), class:"card mt-5 mx-auto text-decoration-none link-dark" do %>
            <% if diary.image.present?%>
              <% if diary.image.content_type.include?('image/')%>
                <%= image_tag diary.image,class: "card-img-top image-fluid" %>
              <% else %>
                <%= video_tag rails_blob_path(diary.image), class: "card-img-top image-fluid",controls: true %>
              <% end%>
            <% end %>
            <div class="text-center fw-bold">
              <%= diary.start_time.strftime("%Y年%m月%d日")%>
              <div class="mt-2">
                <%= diary.user.nickname %>
              </div>
              <div class="mt-2">
                部位: <%= diary.site%>
              </div>
              <table class="table table-bordered mt-3">
                <thead>
                  <th>種目</th>
                  <th>重量</th>
                  <th>回数</th>
                  <th>セット数</th>
                </thead>
              <% diary.workouts.each do |workout|%>
                <tbody>
                  <tr>
                    <td><%= workout.menu%></td>
                    <td class="text-end"><%= workout.weight%></td>
                    <td class="text-end"><%= workout.rep %></td>
                    <td class="text-end"><%= workout.set %></td>
                  </tr>
                </tbody>
              <%end%>
              </table>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/diaries/_workout_fields.html.erb
<div class="nested-fields">
  <div class="d-md-flex mt-2 mb-4">
    <div class="ms-2 me-2"> 
      <%= f.label "種目" %>
      <%=f.text_field :menu, class: "form-control", placeholder: "ベンチプレス" %>
    </div>
    <div class="ms-2 me-2">
      <%= f.label "重量"%>
      <%=f.text_field :weight, class: "form-control",placeholder: "100kg・自重" %>
    </div>
    <div class="ms-2 me-2">
      <%= f.label "回数" %>
      <%= f.text_field :rep, class: "form-control", placeholder: "10"%>
    </div>
    <div class="ms-2 me-2">
      <%= f.label "セット数"%>
      <%= f.text_field :set, class: "form-control",placeholder: "3" %>
    </div>
    <%= link_to_remove_association 'DELETE', f , class:"btn btn-secondary mt-4"%>
  </div>
</div>

app/views/diaries/edit.html.erb
<%= render 'shared/second-header' %>
<div class="bg-light pt-4 d-md-flex align-items-center">
  <div class="mx-auto h-75 w-75 bg-white">
    <div class="fs-4 mb-3 text-center pt-2">記録の情報を入力
    </div>
    <%=form_with model: @diary, id: 'new_diary',class: "row" , local:true do |f| %>
    <%= render 'shared/error_message', model: f.object %>
    <div class=" mt-2 mb-4 mx-auto text-center">
      <%= f.label "記録日", class: "fw-bolder" %>
      <%= f.datetime_field :start_time,class:"form-control w-50 mx-auto" %>
    </div>
    <div class="mx-auto text-center">
      <%= f.label "部位", class: "fw-bold" %>
      <%= f.text_field :site, class: "form-control w-50 mx-auto mb-4", placeholder: "例)　胸・肩（前）, 背中・腹筋など" %>
    </div>
    
    <%= f.fields_for :workouts do |form|%>
      <%= render 'workout_fields',f: form %>
    <% end%>
    <div id="detail-association-insertion-point"></div>

    <div class=" d-grid gap-2 mb-4 w-50 mx-auto">
      <%= link_to_add_association "メニューを追加する", f,:workouts,class:"btn btn-outline-primary",id: "add-btn",
        data:{
          association_insertion_node: '#detail-association-insertion-point',
          association_insertion_method: 'before'
          } 
          %>
    </div>
    <div class="input-group mb-3 w-75 mx-auto">
      <%= f.label "画像または動画" ,class:"input-group-text", for:"inputGroupFile01" %>
      <%= f.file_field :image,  class:"form-control", id:"inputGroupFile01"%>
    </div>
    <div id="previews"></div>
    <div class="d-grid gap-2 col-6 mx-auto mb-4 mt-4">
      <%= f.submit "更新する",class:"btn btn-danger" %>
      <%= link_to '戻る', diary_path(@diary), class: "btn btn-secondary" %>
    </div>
    <% end %>
  </div>
</div>

<%= render 'shared/second-footer'%>

app/views/diaries/index.html.erb
<%= render 'shared/header.html.erb' %>

<%= render 'diary' %>

<%= render 'shared/record' %>
<%= render 'shared/second-footer' %>

app/views/diaries/new.html.erb
<%= render 'shared/second-header' %>
<div class="bg-light pt-4 d-md-flex align-items-center">
  <div class="mx-auto h-75 w-75 bg-white">
    <div class="fs-4 mb-3 text-center pt-2">記録の情報を入力
    </div>
    <%=form_with model: @diary, id: 'new_diary',class: "row", local:true do |f| %>
    <%= render 'shared/error_message', model: f.object %>
    <div class=" mt-2 mb-4 mx-auto text-center">
      <%= f.label "記録日", class: "fw-bolder" %>
      <%= f.datetime_field :start_time ,class:"form-control w-50 mx-auto" %>
    </div>
    <div class="mx-auto text-center">
      <%= f.label "部位", class: "fw-bold" %>
      <%= f.text_field :site, class: "form-control w-50 mx-auto mb-4", placeholder: "例)　胸・肩（前）, 背中・腹筋など" %>
    </div>
    
    <%= f.fields_for :workouts do |form|%>
      <%= render 'workout_fields',f: form %>
    <% end%>
    <div id="detail-association-insertion-point"></div>

    <div class=" d-grid gap-2 mb-4 w-50 mx-auto">
      <%= link_to_add_association "メニューを追加する", f,:workouts,class:"btn btn-outline-primary",id: "add-btn",
        data:{
          association_insertion_node: '#detail-association-insertion-point',
          association_insertion_method: 'before'
          } 
          %>
    </div>
    <div class="input-group mb-3 w-75 mx-auto">
      <%= f.label "画像または動画" ,class:"input-group-text", for:"inputGroupFile01" %>
      <%= f.file_field :image,  class:"form-control", id:"inputGroupFile01"%>
    </div>
    <div id="previews"></div>
    <div class="d-grid gap-2 col-6 mx-auto mb-4 mt-4">
      <%= f.submit "記録する",class:"btn btn-danger" %>
    </div>
    <% end %>
  </div>
</div>
<%= render 'shared/second-footer'%>

app/views/diaries/search.html.erb
<%= render 'shared/header'%>

<%= render 'diary' %>

<%= render 'shared/record' %>

<%= render 'shared/second-footer' %>

app/views/diaries/show.html.erb
<%= render 'shared/second-header' %>

<div class="bg-light pt-4">
  <div class="container">
    <div class="col-md-12">
      <div class="card mx-auto">
        <%= link_to user_path(@diary.user.id) , class:"d-flex justify-content-center fs-4 pt-3 pb-3 link-dark text-decoration-none" do %>
          記録者：<%= @diary.user.nickname%>
        <% end %>
        <div class="d-flex justify-content-center pt-3 pb-3">
          <%= link_to "#{@diary.user.nickname}の頻度カレンダーを見る", user_calendar_path(@diary.user), class: "btn btn-primary" %>
        </div>
        <div class="mx-auto">
          <% if @diary.image.present?%>
            <% if @diary.image.content_type.include?('image/')%>
              <%= image_tag @diary.image, class:"card-img-top image-fluid" %>
            <% else %>
              <%= video_tag rails_blob_path(@diary.image), class: "card-img-top image-fluid", controls: true %>
            <% end%>
          <% end %>
          <div class="text-center fw-bold">
            <%= @diary.start_time.strftime("%Y年%m月%d日")%>
            <div class="mt-2">
              部位: <%= @diary.site%>
            </div>
          </div>
          <table class="table table-bordered mt-5">
            <thead>
              <th>種目</th>
              <th>重量</th>
              <th>回数</th>
              <th>セット数</th>
            </thead>
            <% @workouts.each do |workout|%>
              <tbody>
                <tr>
                  <td><%= workout.menu%></td>
                  <td class="text-end"><%= workout.weight%></td>
                  <td class="text-end"><%= workout.rep %></td>
                  <td class="text-end"><%= workout.set %></td>
                </tr>
              </tbody>
            <%end%>
          </table>
        </div>
        <% if user_signed_in? && @diary.user_id == current_user.id%>
          <div class="d-flex justify-content-center pb-3">
            <%= link_to '編集する',edit_diary_path(@diary) , class: "btn btn-primary me-3"%>
            <%= link_to '削除する', diary_path(@diary),method: :delete ,class: "btn btn-danger ms-3",data: {confirm: "本当に削除しますか？"} %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= render 'shared/record' %>
<%= render 'shared/second-footer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkoutDiary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_message.html.erb
<% if model.errors.any? %>
<div class="d-flex justify-content-center">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='text-danger'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<div class="sticky-top">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <%= link_to(root_path ,class:"navbar-brand fs-3 d-flex") do %>
        <%= image_tag "musle.png", :size => "50x50" %>
        <span class="fs-3">WorkoutDiary</span>
      <% end %>
      <button class="navbar-toggler " type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent" >
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <% if user_signed_in?%>          
            <li class="nav-item">
              <%= link_to '自分の日記を見る',user_path(current_user.id) ,class:"nav-link active" %>
            </li>
            <li class="nav-item">
              <%=link_to '頻度カレンダーを見る',user_calendars_path(current_user),class:"nav-link" %>
            </li>
          <% end %>
        </ul>
        <%=form_with(url: search_diaries_path, local: true, method: :get, class:"d-flex") do |f| %>
          <%= f.text_field :keyword, class:"form-control", placeholder:"検索" %>
          <%= image_submit_tag "search.svg", class:"btn btn-outline-primary" %>
        <% end %>
      </div>
    </div> 
  </nav>
  <div class="d-grid gap-2 bg-light d-flex justify-content-end pe-2 pb-2">
    <% if user_signed_in? %>
      <div class="pt-2 me-2 fw-bold">
        <%= current_user.nickname %>
      </div>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn btn-outline-primary" %>
    <% else %>
      <%= link_to 'ログイン', new_user_session_path , class:"btn btn-primary me-md-2" %>
      <%= link_to '新規登録', new_user_registration_path,  class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/shared/_record.html.erb
<div class= "d-flex justify-content-end fixed-bottom" >
  <%= link_to(new_diary_path,  class: "btn btn-primary rounded-circle p-0 me-5 mb-4 pt-2", :style => "width:5rem;height:5rem;") do%>
    <span class="font-mini">記録する</span>
    <%= image_tag "diary.svg", class: "mt-2" , :size  => "25x25" %>
  <% end%>
</div>

app/views/shared/_second-footer.html.erb
<div class="bg-light text-center">
  <%= image_tag "dumbbells.png", :size => "100x100" %>
  <span class="fs-3">WorkoutDiary</span>
</div>

app/views/shared/_second-header.html.erb
<div class="bg-light pt-5">
  <%= link_to(root_path,class:"text-center  d-flex justify-content-center  text-decoration-none link-dark") do %>
    <%= image_tag "biceps.png", :size => "100x100" %>
    <div>
      <p class="display-4 fts-italic fw-bold fs-4">When my muscles say “No”, I say “Yes!”</p>
      <p class="fw-bold fs-5 mb-0">ー筋肉がNOと叫んだら,私はYES!と答える。</p>
    </div>
  <% end %>
  </div>
</div>

app/views/shered/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">WorkoutDiary</a>
    <button class="navbar-toggler " type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent" >
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex ">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success me-2" type="submit">Search</button>
      </form>
    </div>
    <div class="d-grid gap-2 d-flex justify-content-md-end">
      <%= link_to 'ログイン', new_user_session_path , class:"btn btn-primary me-md-2" %>
      <%= link_to '新規登録', new_user_registration_path,  class: "btn btn-primary" %>
    </div>
  </div>
</nav>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<%= render 'shared/header' %>
<div class="container bg-screen">
  <div class= "p-4 p-md-5 pb-4 text-white">
    <div class="col-md-8 px-0">
      <p class="display-4 fst-italic fs-2">Fitness is not about being better than someone else. It’s about being better than you used to be.</p>
      <p class="fs-4">ーフィットネスは、他人より優れることが重要ではない。かつての自分を超越するものだ。</p>
    </div>
  </div>
</div>
<div class="bg-light">
  <div class="fs-2 text-center pt-4"><%= @user.nickname%>さんのワークアウト日記
  </div>
  <div class="d-flex justify-content-md-center pt-5 pb-1">
    <%= link_to "#{@user.nickname}の頻度カレンダーを見る", user_calendar_path(@user), class: "btn btn-primary" %>
  </div>
  <div class="container">
    <div class="mx-auto">
      <div class="row row-cols-1 row-cols-md-2">
        <% @diaries.each do |diary|%>
        <div class="col">
          <%= link_to diary_path(diary), class:"card mt-5 mx-auto text-decoration-none link-dark" do %>
            <% if diary.image.present?%>
              <% if diary.image.content_type.include?('image/')%>
              <%= image_tag diary.image,class:"card-img-top image-fluid" %>
              <% else %>
              <%= video_tag rails_blob_path(diary.image), class: "card-img-top image-fluid",controls: true %>
              <% end%>
            <% end %>
            <div class="text-center fw-bold">
              <%= diary.start_time.strftime("%Y年%m月%d日")%>
              <div class="mt-2">
                部位: <%= diary.site%>
              </div>
              <table class="table table-bordered mt-3">
                <thead>
                  <th>種目</th>
                  <th>重量</th>
                  <th>回数</th>
                  <th>セット数</th>
                </thead>
              <% diary.workouts.each do |workout|%>
                <tbody>
                  <tr>
                    <td><%= workout.menu%></td>
                    <td class="text-end"><%= workout.weight%></td>
                    <td class="text-end"><%= workout.rep %></td>
                    <td class="text-end"><%= workout.set %></td>
                  </tr>
                </tbody>
              <%end%>
              </table>
            </div>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= render 'shared/record'%>
<%= render 'shared/second-footer' %>